// <auto-generated />
namespace App472.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddDomainEntities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDomainEntities));
        
        string IMigrationMetadata.Id
        {
            get { return "202501130414317_AddDomainEntities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
