// <auto-generated />
namespace App472.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DomainEntities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DomainEntities));
        
        string IMigrationMetadata.Id
        {
            get { return "202501290711545_DomainEntities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
